function f = economic_F(t,J,N,E,c1,c2,delta,k,p,q,r)
%ECONOMIC_F
%    F = ECONOMIC_F(T,J,N,E,C1,C2,DELTA,K,P,Q,R)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    17-Jan-2015 10:58:17

f = [-E.*N.*q-N.*r.*(N./k-1.0);exp(-delta.*t).*(E.*c1+E.^2.*c2-E.*N.*p.*q)];
