function dfdu_times_v = economic_dFdu_times_vec(t,J,N,E,v1,v2,c1,c2,delta,p,q)
%ECONOMIC_DFDU_TIMES_VEC
%    DFDU_TIMES_V = ECONOMIC_DFDU_TIMES_VEC(T,J,N,E,V1,V2,C1,C2,DELTA,P,Q)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    17-Jan-2015 10:58:17

dfdu_times_v = reshape([-N.*q.*v1+v2.*exp(-delta.*t).*(c1+E.*c2.*2.0-N.*p.*q)],[1, 1]);
