function dfdx_times_v = economic_dFdx_times_vec(t,J,N,E,v1,v2,delta,k,p,q,r)
%ECONOMIC_DFDX_TIMES_VEC
%    DFDX_TIMES_V = ECONOMIC_DFDX_TIMES_VEC(T,J,N,E,V1,V2,DELTA,K,P,Q,R)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    17-Jan-2015 10:58:17

t2 = 1.0./k;
dfdx_times_v = [-v1.*(E.*q+r.*(N.*t2-1.0)+N.*r.*t2)-E.*p.*q.*v2.*exp(-delta.*t);0.0];
