function dfdu_times_v = engineering_dFdu_times_vec(t,N,E,J,u,v1,v2,v3,c3,delta)
%ENGINEERING_DFDU_TIMES_VEC
%    DFDU_TIMES_V = ENGINEERING_DFDU_TIMES_VEC(T,N,E,J,U,V1,V2,V3,C3,DELTA)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    17-Jan-2015 12:30:20

dfdu_times_v = reshape([v2+c3.*u.*v3.*exp(-delta.*t).*2.0],[1, 1]);
