function dfdx_times_v = engineering_dFdx_times_vec(t,N,E,J,u,v1,v2,v3,c1,delta,k,p,q,r)
%ENGINEERING_DFDX_TIMES_VEC
%    DFDX_TIMES_V = ENGINEERING_DFDX_TIMES_VEC(T,N,E,J,U,V1,V2,V3,C1,DELTA,K,P,Q,R)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    17-Jan-2015 12:30:20

t2 = 1.0./k;
t3 = exp(-delta.*t);
dfdx_times_v = [-v1.*(E.*q+r.*(N.*t2-1.0)+N.*r.*t2)-E.*p.*q.*t3.*v3;-N.*q.*v1+t3.*v3.*(c1-N.*p.*q);0.0];
