function f = engineering_F(t,N,E,J,u,c1,c3,delta,k,p,q,r)
%ENGINEERING_F
%    F = ENGINEERING_F(T,N,E,J,U,C1,C3,DELTA,K,P,Q,R)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    17-Jan-2015 12:30:19

f = [-E.*N.*q-N.*r.*(N./k-1.0);u;exp(-delta.*t).*(E.*c1+c3.*u.^2-E.*N.*p.*q)];
